modLoader="javafml"
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
issueTrackerURL="https://github.com/TJT01/LapisLib/issues"

[[mods]]
modId="lapislib"
version="1.20.1-1.3.1"
displayName="LapisLib"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
# logoFile="examplemod.png"
# credits="Thanks for this example mod goes to Java"
authors="TJT01" #optional
description='''
It's a library.
'''

[[dependencies.lapislib]]
    modId="forge"
    mandatory=true
    versionRange="[47.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lapislib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
