name: Publish
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ZSQQy6SM
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
            
          curseforge-id: 584858
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
